name: build chrome-devtools-frontend

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH

    - name: Checking out source
      run: |
        git clone https://chromium.googlesource.com/devtools/devtools-frontend
        gclient config https://chromium.googlesource.com/devtools/devtools-frontend --unmanaged

    - name: Build
      run: |
        gclient sync
        gn gen out/Default
        autoninja -C out/Default
      working-directory: devtools-frontend

    - name: Display release
      run: ls -R
      working-directory: devtools-frontend/out/Default/gen/front_end

    - name: Gzip
      run: |
        mkdir devtools-release
        cp -r devtools-frontend/out/Default/gen/front_end devtools-release
        tar -czvf  devtools-release.tar.gz  devtools-release

    - name: Set version
      id: output-name
      run: |
        current=`date "+%Y-%m-%d %H:%M:%S"`
        timeStamp=`date -d "$current" +%s`
        currentTimeStamp=$(((timeStamp*1000+10#`date "+%N"`/1000000)/1000)) #将current转换为时间戳，精确到秒
        echo "version=$currentTimeStamp" >> $GITHUB_OUTPUT

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
      with:
        tag_name: version-${{ steps.output-name.outputs.version }}
        files: devtools-release.tar.gz

    # - name: Upload to release
    #   uses: JasonEtco/upload-to-release@master
    #   with:
    #     args:  devtools-release.tar.gz application/octet-stream
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}



