name: build chrome-devtools-frontend

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH

    - name: Checking out source
      run: |
        git clone --depth=1 https://chromium.googlesource.com/devtools/devtools-frontend
        gclient config https://chromium.googlesource.com/devtools/devtools-frontend --unmanaged

    - name: Build
      run: |
        gclient sync
        gn gen out/Default
        autoninja -C out/Default
      working-directory: devtools-frontend

    - name: Display release
      run: ls -R
      working-directory: devtools-frontend/out/Default/gen/front_end

    - name: Gzip
      run: |
        # mkdir devtools-release
        # cp -r devtools-frontend/out/Default/gen/front_end devtools-release
        tar -czvf  devtools-release.tar.gz -C devtools-frontend/out/Default/gen front_end
        tar --exclude="*.grd" --exclude="*.js.map" --exclude="*.d.ts" --exclude="*-tsconfig.json" -czvf devtools-release-slim.tar.gz -C devtools-frontend/out/Default/gen front_end

    - name: Set version
      id: output-name
      run: |
        COMMIT_HASH=`git rev-parse --short HEAD` # 记录提交hash
        echo "version=$COMMIT_HASH" >> $GITHUB_OUTPUT
        git show --no-patch > ${{ github.workspace }}-CHANGELOG.txt
      working-directory: devtools-frontend

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
      with:
        tag_name: version-${{ steps.output-name.outputs.version }}
        files: |
          devtools-release.tar.gz
          devtools-release-slim.tar.gz
        body_path: ${{ github.workspace }}-CHANGELOG.txt


